import { User, Tune, LavajamRecord, AttendanceSession } from '@/types/band';

const now = new Date();
const daysAgo = (days: number) => {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user-overall-1',
    name: 'Mufaddal Bhai',
    email: 'overall.major@taheriscout.org',
    role: 'Overall Major',
    section: 'Trumpet',
    phone: '+91 98200 11223',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rank: 'Band Commander / Overall Major',
    joinedDate: '2018-01-15',
    active: true,
  },
  {
    id: 'user-treasurer-1',
    name: 'Huzefa Bhai',
    email: 'treasurer@taheriscout.org',
    role: 'Treasurer',
    section: 'SideDrum',
    phone: '+91 98200 33445',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rank: 'Chief Financial Officer',
    joinedDate: '2019-03-10',
    active: true,
  },
  {
    id: 'user-trumpet-major',
    name: 'Taher Mandsorwala',
    email: 'trumpet.major@taheriscout.org',
    role: 'Trumpet Major',
    section: 'Trumpet',
    phone: '+91 98200 55667',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rank: 'Section Leader - Trumpet',
    joinedDate: '2020-02-01',
    active: true,
  },
  {
    id: 'user-sax-major',
    name: 'Mustafa Bhai',
    email: 'sax.major@taheriscout.org',
    role: 'Saxophone Major',
    section: 'Saxophone',
    phone: '+91 98200 77889',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    rank: 'Section Leader - Saxophone',
    joinedDate: '2020-04-12',
    active: true,
  },
  {
    id: 'user-euph-major',
    name: 'Abbas Bhai',
    email: 'euphonium.major@taheriscout.org',
    role: 'Euphonium Major',
    section: 'Euphonium',
    phone: '+91 98200 99001',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    rank: 'Section Leader - Euphonium',
    joinedDate: '2021-01-20',
    active: true,
  },
  {
    id: 'user-dish-major',
    name: 'Burhanuddin Bhai',
    email: 'dish.major@taheriscout.org',
    role: 'Dish Major',
    section: 'Dish',
    phone: '+91 98200 12345',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    rank: 'Section Leader - Cymbals/Dish',
    joinedDate: '2021-05-15',
    active: true,
  },
  {
    id: 'user-drum-major',
    name: 'Husain Bhai',
    email: 'sidedrum.major@taheriscout.org',
    role: 'SideDrum Major',
    section: 'SideDrum',
    phone: '+91 98200 67890',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    rank: 'Section Leader - Percussion/SideDrum',
    joinedDate: '2020-11-05',
    active: true,
  },

  // Trumpet Players
  {
    id: 'player-t-1',
    name: 'Ali Asgar',
    email: 'aliasgar.trumpet@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Trumpet',
    phone: '+91 98111 22334',
    rank: 'Senior Trumpeter (1st Voice)',
    joinedDate: '2022-01-10',
    active: true,
  },
  {
    id: 'player-t-2',
    name: 'Idris Bhai',
    email: 'idris.trumpet@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Trumpet',
    phone: '+91 98111 33445',
    rank: 'Trumpeter (2nd Voice)',
    joinedDate: '2022-06-15',
    active: true,
  },
  {
    id: 'player-t-3',
    name: 'Murtaza K',
    email: 'murtaza.trumpet@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Trumpet',
    phone: '+91 98111 44556',
    rank: 'Junior Trumpeter',
    joinedDate: '2023-08-01',
    active: true,
  },

  // Saxophone Players
  {
    id: 'player-s-1',
    name: 'Shabbir Bhai',
    email: 'shabbir.sax@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Saxophone',
    phone: '+91 98111 55667',
    rank: 'Alto Saxophonist',
    joinedDate: '2022-03-12',
    active: true,
  },
  {
    id: 'player-s-2',
    name: 'Yusuf M',
    email: 'yusuf.sax@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Saxophone',
    phone: '+91 98111 66778',
    rank: 'Tenor Saxophonist',
    joinedDate: '2023-02-18',
    active: true,
  },

  // Euphonium Players
  {
    id: 'player-e-1',
    name: 'Ibrahim S',
    email: 'ibrahim.euph@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Euphonium',
    phone: '+91 98111 77889',
    rank: 'Euphonium Player',
    joinedDate: '2022-09-05',
    active: true,
  },
  {
    id: 'player-e-2',
    name: 'Khadim H',
    email: 'khadim.euph@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Euphonium',
    phone: '+91 98111 88990',
    rank: 'Baritone / Euphonium',
    joinedDate: '2023-11-20',
    active: true,
  },

  // Dish Players
  {
    id: 'player-d-1',
    name: 'Qasim B',
    email: 'qasim.dish@taheriscout.org',
    role: 'Band Member / Player',
    section: 'Dish',
    phone: '+91 98111 99001',
    rank: 'Lead Cymbals / Dish',
    joinedDate: '2022-04-14',
    active: true,
  },

  // SideDrum Players
  {
    id: 'player-sd-1',
    name: 'Zainuddin S',
    email: 'zainuddin.drum@taheriscout.org',
    role: 'Band Member / Player',
    section: 'SideDrum',
    phone: '+91 98111 11223',
    rank: 'Snare Drummer (Cadence Lead)',
    joinedDate: '2021-08-10',
    active: true,
  },
  {
    id: 'player-sd-2',
    name: 'Ammar F',
    email: 'ammar.drum@taheriscout.org',
    role: 'Band Member / Player',
    section: 'SideDrum',
    phone: '+91 98111 22335',
    rank: 'Side Drummer',
    joinedDate: '2023-04-01',
    active: true,
  },
];

export const INITIAL_TUNES: Tune[] = [
  {
    id: 'tune-1',
    title: 'Burhanedin Chaman Tera',
    section: 'Trumpet',
    key: 'burhandeen_chaman_tera_notes',
    pdfUrl: '/tunes/burhandeen_chaman_tera_notes.pdf',
    audioUrl: 'https://www.youtube.com/watch?v=QM1UC7O0sWI',
    driveFileId: '1dr_burhanedin_001',
    createdAt: daysAgo(45), // > 15 days (not new)
    uploadedBy: 'user-trumpet-major',
    assignedUserIds: ['player-t-1', 'player-t-2', 'player-t-3'],
    difficulty: 'Intermediate',
    tempo: '112 BPM',
  },
  {
    id: 'tune-2',
    title: 'Hubbi Lakum',
    section: 'Trumpet',
    key: 'hubbi_lakum_notes',
    pdfUrl: '/tunes/hubbi_lakum_notes.pdf',
    audioUrl: 'https://www.youtube.com/watch?v=LNvkhv3IDlg',
    driveFileId: '1dr_hubbi_002',
    createdAt: daysAgo(30), // > 15 days (not new)
    uploadedBy: 'user-trumpet-major',
    assignedUserIds: ['player-t-1', 'player-t-2'],
    difficulty: 'Beginner',
    tempo: '96 BPM',
  },
  {
    id: 'tune-3',
    title: 'Is Shamme Huda Ka Jo',
    section: 'Trumpet',
    key: 'Iss_shame_huda_ka_jo_notes',
    pdfUrl: '/tunes/Iss_shame_huda_ka_jo_notes.pdf',
    audioUrl: 'https://www.youtube.com/watch?v=Xgkk1vOy8Zk',
    driveFileId: '1dr_iss_shame_003',
    createdAt: daysAgo(20), // > 15 days (not new)
    uploadedBy: 'user-trumpet-major',
    assignedUserIds: ['player-t-1', 'player-t-2', 'player-t-3'],
    difficulty: 'Advanced',
    tempo: '120 BPM',
  },
  {
    id: 'tune-4',
    title: 'Hai Tahani',
    section: 'Trumpet',
    key: 'hai_tahani_notes',
    pdfUrl: '/tunes/hai_tahani_notes.pdf',
    audioUrl: 'https://www.youtube.com/watch?v=x_wVH4o266Y',
    driveFileId: '1dr_hai_tahani_004',
    createdAt: daysAgo(3), // 3 days ago: PROMINENT "NEW" BADGE!
    uploadedBy: 'user-overall-1',
    assignedUserIds: ['player-t-1', 'player-t-2', 'player-t-3'],
    difficulty: 'Intermediate',
    tempo: '108 BPM',
  },
  {
    id: 'tune-5',
    title: 'Trumpet Notations Master Sheet',
    section: 'Trumpet',
    key: 'trumpet_notation_notes',
    pdfUrl: '/tunes/trumpet_notation_notes.pdf',
    driveFileId: '1dr_notation_005',
    createdAt: daysAgo(6), // 6 days ago: PROMINENT "NEW" BADGE!
    uploadedBy: 'user-trumpet-major',
    assignedUserIds: ['player-t-1', 'player-t-3'],
    difficulty: 'Beginner',
    tempo: 'Standard Scales',
  },
  {
    id: 'tune-6',
    title: 'Marsiyah Hymn No. 4',
    section: 'Saxophone',
    key: 'marsiyah_hymn_sax',
    pdfUrl: '/tunes/hai_tahani_notes.pdf',
    driveFileId: '1dr_sax_001',
    createdAt: daysAgo(5), // 5 days ago: PROMINENT "NEW" BADGE!
    uploadedBy: 'user-sax-major',
    assignedUserIds: ['player-s-1', 'player-s-2'],
    difficulty: 'Intermediate',
    tempo: '100 BPM',
  },
  {
    id: 'tune-7',
    title: 'Salwaat Anthem Cadence',
    section: 'SideDrum',
    key: 'salwaat_cadence_drum',
    pdfUrl: '/tunes/trumpet_notation_notes.pdf',
    driveFileId: '1dr_drum_001',
    createdAt: daysAgo(2), // 2 days ago: PROMINENT "NEW" BADGE!
    uploadedBy: 'user-drum-major',
    assignedUserIds: ['player-sd-1', 'player-sd-2'],
    difficulty: 'Advanced',
    tempo: '128 BPM',
  },
  {
    id: 'tune-8',
    title: 'Euphonium Bass Line - Chaman Tera',
    section: 'Euphonium',
    key: 'euph_chaman_tera',
    pdfUrl: '/tunes/burhandeen_chaman_tera_notes.pdf',
    driveFileId: '1dr_euph_001',
    createdAt: daysAgo(60),
    uploadedBy: 'user-euph-major',
    assignedUserIds: ['player-e-1'],
    difficulty: 'Intermediate',
    tempo: '112 BPM',
  },
  {
    id: 'tune-9',
    title: 'Royal Procession Cymbals March',
    section: 'Dish',
    key: 'dish_procession_march',
    pdfUrl: '/tunes/hubbi_lakum_notes.pdf',
    driveFileId: '1dr_dish_001',
    createdAt: daysAgo(10), // 10 days ago: PROMINENT "NEW" BADGE!
    uploadedBy: 'user-dish-major',
    assignedUserIds: ['player-d-1'],
    difficulty: 'Beginner',
    tempo: '116 BPM',
  },
];

export const INITIAL_LAVAJAM: LavajamRecord[] = [
  {
    id: 'lav-001',
    userId: 'player-t-1',
    userName: 'Ali Asgar',
    section: 'Trumpet',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(5),
    paymentMethod: 'UPI',
    transactionRef: 'UPI/20260912/882109',
    receiptNo: 'REC-2026-091',
    notes: 'Band uniform maintenance & tune sheet subscription',
  },
  {
    id: 'lav-002',
    userId: 'player-t-2',
    userName: 'Idris Bhai',
    section: 'Trumpet',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Pending',
    notes: 'Followed up via SMS on 14th Sep',
  },
  {
    id: 'lav-003',
    userId: 'player-t-3',
    userName: 'Murtaza K',
    section: 'Trumpet',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(2),
    paymentMethod: 'Cash',
    transactionRef: 'CASH-REC-092',
    receiptNo: 'REC-2026-092',
    notes: 'Collected at Sunday practice',
  },
  {
    id: 'lav-004',
    userId: 'player-s-1',
    userName: 'Shabbir Bhai',
    section: 'Saxophone',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(9),
    paymentMethod: 'Bank Transfer',
    transactionRef: 'NEFT/HDFC/99218273',
    receiptNo: 'REC-2026-093',
  },
  {
    id: 'lav-005',
    userId: 'player-s-2',
    userName: 'Yusuf M',
    section: 'Saxophone',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Pending',
    notes: 'Requested extension till month end',
  },
  {
    id: 'lav-006',
    userId: 'player-e-1',
    userName: 'Ibrahim S',
    section: 'Euphonium',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(8),
    paymentMethod: 'UPI',
    transactionRef: 'UPI/20260909/771234',
    receiptNo: 'REC-2026-094',
  },
  {
    id: 'lav-007',
    userId: 'player-e-2',
    userName: 'Khadim H',
    section: 'Euphonium',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Pending',
  },
  {
    id: 'lav-008',
    userId: 'player-d-1',
    userName: 'Qasim B',
    section: 'Dish',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(11),
    paymentMethod: 'Cash',
    receiptNo: 'REC-2026-095',
  },
  {
    id: 'lav-009',
    userId: 'player-sd-1',
    userName: 'Zainuddin S',
    section: 'SideDrum',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Paid',
    paidAt: daysAgo(7),
    paymentMethod: 'UPI',
    transactionRef: 'UPI/20260910/556611',
    receiptNo: 'REC-2026-096',
  },
  {
    id: 'lav-010',
    userId: 'player-sd-2',
    userName: 'Ammar F',
    section: 'SideDrum',
    year: 2026,
    month: 'September',
    amount: 1500,
    status: 'Pending',
  },
];

export const INITIAL_ATTENDANCE_SESSIONS: AttendanceSession[] = [
  {
    id: 'att-session-001',
    date: daysAgo(1),
    sessionTitle: 'Weekly Parade & National Anthem Drill',
    sessionType: 'Parade Drill',
    markedBy: 'user-overall-1',
    records: [
      { userId: 'user-trumpet-major', userName: 'Taher Mandsorwala', section: 'Trumpet', status: 'Present' },
      { userId: 'user-sax-major', userName: 'Mustafa Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'user-euph-major', userName: 'Abbas Bhai', section: 'Euphonium', status: 'Present' },
      { userId: 'user-dish-major', userName: 'Burhanuddin Bhai', section: 'Dish', status: 'Present' },
      { userId: 'user-drum-major', userName: 'Husain Bhai', section: 'SideDrum', status: 'Present' },
      { userId: 'player-t-1', userName: 'Ali Asgar', section: 'Trumpet', status: 'Present' },
      { userId: 'player-t-2', userName: 'Idris Bhai', section: 'Trumpet', status: 'Late', notes: 'Arrived 15m late with notice' },
      { userId: 'player-t-3', userName: 'Murtaza K', section: 'Trumpet', status: 'Present' },
      { userId: 'player-s-1', userName: 'Shabbir Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'player-s-2', userName: 'Yusuf M', section: 'Saxophone', status: 'Absent', notes: 'Out of station' },
      { userId: 'player-e-1', userName: 'Ibrahim S', section: 'Euphonium', status: 'Present' },
      { userId: 'player-e-2', userName: 'Khadim H', section: 'Euphonium', status: 'Present' },
      { userId: 'player-d-1', userName: 'Qasim B', section: 'Dish', status: 'Present' },
      { userId: 'player-sd-1', userName: 'Zainuddin S', section: 'SideDrum', status: 'Present' },
      { userId: 'player-sd-2', userName: 'Ammar F', section: 'SideDrum', status: 'Excused', notes: 'Exams' },
    ],
  },
  {
    id: 'att-session-002',
    date: daysAgo(4),
    sessionTitle: 'Sectional Harmony Practice - Brass & Woodwinds',
    sessionType: 'Sectional',
    markedBy: 'user-overall-1',
    records: [
      { userId: 'user-trumpet-major', userName: 'Taher Mandsorwala', section: 'Trumpet', status: 'Present' },
      { userId: 'user-sax-major', userName: 'Mustafa Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'user-euph-major', userName: 'Abbas Bhai', section: 'Euphonium', status: 'Present' },
      { userId: 'player-t-1', userName: 'Ali Asgar', section: 'Trumpet', status: 'Present' },
      { userId: 'player-t-2', userName: 'Idris Bhai', section: 'Trumpet', status: 'Present' },
      { userId: 'player-t-3', userName: 'Murtaza K', section: 'Trumpet', status: 'Present' },
      { userId: 'player-s-1', userName: 'Shabbir Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'player-s-2', userName: 'Yusuf M', section: 'Saxophone', status: 'Present' },
      { userId: 'player-e-1', userName: 'Ibrahim S', section: 'Euphonium', status: 'Present' },
      { userId: 'player-e-2', userName: 'Khadim H', section: 'Euphonium', status: 'Absent' },
    ],
  },
  {
    id: 'att-session-003',
    date: daysAgo(8),
    sessionTitle: 'Full Scout Band General Rehearsal',
    sessionType: 'Regular Practice',
    markedBy: 'user-overall-1',
    records: [
      { userId: 'user-trumpet-major', userName: 'Taher Mandsorwala', section: 'Trumpet', status: 'Present' },
      { userId: 'user-sax-major', userName: 'Mustafa Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'user-euph-major', userName: 'Abbas Bhai', section: 'Euphonium', status: 'Present' },
      { userId: 'user-dish-major', userName: 'Burhanuddin Bhai', section: 'Dish', status: 'Present' },
      { userId: 'user-drum-major', userName: 'Husain Bhai', section: 'SideDrum', status: 'Present' },
      { userId: 'player-t-1', userName: 'Ali Asgar', section: 'Trumpet', status: 'Present' },
      { userId: 'player-t-2', userName: 'Idris Bhai', section: 'Trumpet', status: 'Present' },
      { userId: 'player-t-3', userName: 'Murtaza K', section: 'Trumpet', status: 'Present' },
      { userId: 'player-s-1', userName: 'Shabbir Bhai', section: 'Saxophone', status: 'Present' },
      { userId: 'player-s-2', userName: 'Yusuf M', section: 'Saxophone', status: 'Present' },
      { userId: 'player-e-1', userName: 'Ibrahim S', section: 'Euphonium', status: 'Present' },
      { userId: 'player-e-2', userName: 'Khadim H', section: 'Euphonium', status: 'Present' },
      { userId: 'player-d-1', userName: 'Qasim B', section: 'Dish', status: 'Present' },
      { userId: 'player-sd-1', userName: 'Zainuddin S', section: 'SideDrum', status: 'Present' },
      { userId: 'player-sd-2', userName: 'Ammar F', section: 'SideDrum', status: 'Present' },
    ],
  },
];
